// packages/angular-charts/src/histogram.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { createLinearScale, computeExtent, computeHistogramBins } from '@refraction-ui/charts';
import { ChartContextService } from './chart-context.service';

@Component({
  selector: '[re-histogram]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg:rect
      *ngFor="let bin of computedBins"
      [attr.x]="bin.x"
      [attr.y]="bin.y"
      [attr.width]="bin.width"
      [attr.height]="bin.height"
      [attr.fill]="fill"
    />
  `
})
export class HistogramComponent<T = any> {
  @Input() data: T[] = [];
  @Input() value!: (d: T) => number;
  @Input() bins: number = 10;
  @Input() fill: string = 'currentColor';

  constructor(private contextService: ChartContextService) {}

  get computedBins() {
    const dimensions = this.contextService.context().dimensions;
    const { boundedWidth, boundedHeight } = dimensions;

    const data = this.data;
    if (!data || !data.length || !this.value) return [];

    const values = data.map(this.value);
    const [minVal, maxVal] = computeExtent(values);
    const histogramBins = computeHistogramBins(values, this.bins);
    const maxCount = Math.max(...histogramBins.map(b => b.count));

    const xScale = createLinearScale([minVal as number, maxVal as number], [0, boundedWidth]);
    const yScale = createLinearScale([0, maxCount], [boundedHeight, 0]);

    return histogramBins.map(bin => {
      const xPos = xScale(bin.x0);
      const width = Math.max(0, xScale(bin.x1) - xScale(bin.x0) - 1);
      const yPos = yScale(bin.count);
      const height = Math.max(0, boundedHeight - yPos);

      return { x: xPos, y: yPos, width, height };
    });
  }
}

// packages/react-charts/src/histogram.tsx
import * as React from 'react'
import {
  computeHistogramBins,
  createLinearScale,
  createBandScale,
  combineDimensions,
  formatTick,
} from '@refraction-ui/charts'
import type { Margin } from '@refraction-ui/charts'

export interface HistogramProps {
  data: number[]
  width?: number
  height?: number
  bins?: number
  fill?: string
  margin?: Partial<Margin>
  className?: string
}

export function Histogram({
  data,
  width = 600,
  height = 400,
  bins: binCount = 10,
  fill = 'steelblue',
  margin,
  className,
}: HistogramProps) {
  const dimensions = combineDimensions({ width, height, margin })
  const { boundedWidth, boundedHeight } = dimensions

  const histBins = computeHistogramBins(data, binCount)
  const maxCount = Math.max(...histBins.map((b) => b.count))

  const labels = histBins.map((b) => `${formatTick(b.x0, 'number')}-${formatTick(b.x1, 'number')}`)
  const xScale = createBandScale(labels, [0, boundedWidth], 0.05)
  const yScale = createLinearScale([0, maxCount], [boundedHeight, 0])

  const yTicks = yScale.ticks(5)

  return (
    <svg width={width} height={height} className={className}>
      <g transform={`translate(${dimensions.margin.left},${dimensions.margin.top})`}>
        {histBins.map((bin, i) => {
          const label = labels[i]
          const barX = xScale(label)
          const barY = yScale(bin.count)
          const barHeight = boundedHeight - barY
          const barWidth = xScale.bandwidth()
          return (
            <rect
              key={i}
              x={barX}
              y={barY}
              width={barWidth}
              height={barHeight}
              fill={fill}
            />
          )
        })}
        {/* X Axis */}
        <g transform={`translate(0,${boundedHeight})`}>
          {labels.map((label, i) => {
            const x = xScale(label) + xScale.bandwidth() / 2
            return (
              <g key={i} transform={`translate(${x},0)`}>
                <line y2={6} stroke="currentColor" />
                <text y={18} textAnchor="middle" fontSize={10} fill="currentColor">
                  {label}
                </text>
              </g>
            )
          })}
        </g>
        {/* Y Axis */}
        <g>
          {yTicks.map((tick, i) => {
            const y = yScale(tick)
            return (
              <g key={i} transform={`translate(0,${y})`}>
                <line x2={-6} stroke="currentColor" />
                <text x={-9} dy="0.32em" textAnchor="end" fontSize={10} fill="currentColor">
                  {formatTick(tick, 'number')}
                </text>
              </g>
            )
          })}
        </g>
      </g>
    </svg>
  )
}
