// packages/angular-charts/src/line.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { linePath, areaPath, createLinearScale, createTimeScale, computeExtent } from '@refraction-ui/charts';
import { ChartContextService } from './chart-context.service';

@Component({
  selector: '[re-line]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg:path *ngIf="computedArea" [attr.d]="computedArea" [attr.fill]="fill" opacity="0.2" />
    <svg:path [attr.d]="computedPath" fill="none" [attr.stroke]="stroke" [attr.stroke-width]="strokeWidth" />
  `
})
export class LineComponent<T = any> {
  @Input() data: T[] = [];
  @Input() x!: (d: T) => number | Date;
  @Input() y!: (d: T) => number;
  @Input() curve: 'linear' | 'monotoneX' | 'step' = 'monotoneX';
  @Input() stroke: string = 'currentColor';
  @Input() fill?: string;
  @Input() strokeWidth: number = 2;
  @Input() isDate: boolean = false;

  constructor(private contextService: ChartContextService) {}

  get scaleData() {
    const dimensions = this.contextService.context().dimensions;
    const { boundedWidth, boundedHeight } = dimensions;

    const data = this.data;
    if (!data || !data.length || !this.x || !this.y) return null;

    const xVals = data.map(this.x);
    const yVals = data.map(this.y);
    const [minX, maxX] = computeExtent(xVals as number[]);
    const [minY, maxY] = computeExtent(yVals);

    const xScale = this.isDate 
      ? createTimeScale([minX as number, maxX as number], [0, boundedWidth]) 
      : createLinearScale([minX as number, maxX as number], [0, boundedWidth]);
    
    const yScale = createLinearScale([minY as number, maxY as number], [boundedHeight, 0]);

    return { xScale, yScale, boundedHeight };
  }

  get computedPath(): string {
    const scales = this.scaleData;
    if (!scales) return '';
    const { xScale, yScale } = scales;
    return linePath(this.data, (d: T) => xScale(this.x(d) as any), (d: T) => yScale(this.y(d)), this.curve) || '';
  }

  get computedArea(): string | null {
    if (!this.fill) return null;
    const scales = this.scaleData;
    if (!scales) return null;
    const { xScale, yScale, boundedHeight } = scales;
    return areaPath(this.data, (d: T) => xScale(this.x(d) as any), (d: T) => yScale(this.y(d)), boundedHeight, this.curve) || null;
  }
}

// packages/react-charts/src/line.tsx
import * as React from 'react'
import { createLinearScale, computeExtent, linePath } from '@refraction-ui/charts'
import { useChartContext } from './chart-context.js'

export interface LineProps<T = unknown> {
  data: T[]
  x: (d: T) => number
  y: (d: T) => number
  stroke?: string
  strokeWidth?: number
  fill?: string
  className?: string
}

export function Line<T>({
  data,
  x,
  y,
  stroke = 'currentColor',
  strokeWidth = 2,
  fill = 'none',
  className,
}: LineProps<T>) {
  const { dimensions } = useChartContext()
  const { boundedWidth, boundedHeight } = dimensions

  const xValues = data.map(x)
  const yValues = data.map(y)
  const [xMin, xMax] = computeExtent(xValues)
  const [yMin, yMax] = computeExtent(yValues)

  const xScale = createLinearScale([xMin, xMax], [0, boundedWidth])
  const yScale = createLinearScale([yMin, yMax], [boundedHeight, 0])

  const points = data.map((d) => ({
    x: xScale(x(d)),
    y: yScale(y(d)),
  }))

  const d = linePath(points)

  return (
    <path
      className={className}
      d={d}
      stroke={stroke}
      strokeWidth={strokeWidth}
      fill={fill}
    />
  )
}
