// packages/angular-charts/src/pie-chart.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { arcPath } from '@refraction-ui/charts';
import { ChartContextService } from './chart-context.service';

@Component({
  selector: '[re-pie-chart]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg:g [attr.transform]="transformString">
      <svg:g *ngFor="let arc of computedArcs">
        <svg:path [attr.d]="arc.path" [attr.fill]="arc.color" stroke="white" stroke-width="1" />
      </svg:g>
    </svg:g>
  `
})
export class PieChartComponent<T = any> {
  @Input() data: T[] = [];
  @Input() value!: (d: T) => number;
  @Input() label?: (d: T) => string;
  @Input() innerRadius: number = 0;
  @Input() colors?: string[];

  constructor(private contextService: ChartContextService) {}

  get transformString() {
    const dimensions = this.contextService.context().dimensions;
    const { boundedWidth, boundedHeight } = dimensions;
    return \`translate(\${boundedWidth / 2},\${boundedHeight / 2})\`;
  }

  get computedArcs() {
    const dimensions = this.contextService.context().dimensions;
    const { boundedWidth, boundedHeight } = dimensions;

    const data = this.data;
    if (!data || !data.length || !this.value) return [];

    const radius = Math.min(boundedWidth, boundedHeight) / 2;
    const values = data.map(this.value);
    const total = values.reduce((a, b) => a + b, 0);

    let currentAngle = 0;
    return data.map((d, i) => {
      const val = this.value(d);
      const startAngle = currentAngle;
      const endAngle = currentAngle + (val / total) * Math.PI * 2;
      currentAngle = endAngle;

      const path = arcPath({
        innerRadius: this.innerRadius,
        outerRadius: radius,
        startAngle,
        endAngle
      });

      return {
        path: path || '',
        label: this.label ? this.label(d) : '',
        color: this.colors && this.colors.length > 0 ? this.colors[i % this.colors.length] : 'currentColor'
      };
    });
  }
}

// packages/react-charts/src/pie-chart.tsx
import * as React from 'react'
import { arcPath } from '@refraction-ui/charts'

const DEFAULT_COLORS = [
  '#4e79a7', '#f28e2b', '#e15759', '#76b7b2',
  '#59a14f', '#edc948', '#b07aa1', '#ff9da7',
  '#9c755f', '#bab0ac',
]

export interface PieChartProps<T = unknown> {
  data: T[]
  value: (d: T) => number
  width?: number
  height?: number
  colors?: string[]
  className?: string
}

export function PieChart<T>({
  data,
  value,
  width = 300,
  height = 300,
  colors = DEFAULT_COLORS,
  className,
}: PieChartProps<T>) {
  const cx = width / 2
  const cy = height / 2
  const radius = Math.min(cx, cy) - 10

  const values = data.map(value)
  const total = values.reduce((sum, v) => sum + v, 0)

  let currentAngle = -Math.PI / 2

  const arcs = data.map((_, i) => {
    const sliceAngle = (values[i] / total) * Math.PI * 2
    const startAngle = currentAngle
    const endAngle = currentAngle + sliceAngle
    currentAngle = endAngle
    return { startAngle, endAngle, color: colors[i % colors.length] }
  })

  return (
    <svg width={width} height={height} className={className}>
      {arcs.map((arc, i) => (
        <path
          key={i}
          d={arcPath(cx, cy, radius, arc.startAngle, arc.endAngle)}
          fill={arc.color}
        />
      ))}
    </svg>
  )
}
