// packages/angular-charts/src/y-axis.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: '[re-y-axis]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg:g *ngFor="let tick of computedTicks" [attr.transform]="tick.transform">
      <svg:line [attr.x2]="-tickSize" stroke="currentColor" />
      <svg:text
        [attr.x]="-(tickSize + 6)"
        alignment-baseline="middle"
        text-anchor="end"
        font-size="12"
        fill="currentColor"
      >
        {{ tick.value }}
      </svg:text>
    </svg:g>
  `
})
export class YAxisComponent {
  @Input() ticks: (number | string)[] = [];
  @Input() scale!: (value: number | string) => number;
  @Input() tickSize: number = 6;

  get computedTicks() {
    if (!this.scale || !this.ticks) return [];
    return this.ticks.map(tick => {
      const y = this.scale(tick);
      return {
        value: tick,
        transform: \`translate(0,\${y})\`
      };
    });
  }
  }
}

// packages/react-charts/src/y-axis.tsx
import * as React from 'react'

export interface YAxisProps {
  ticks: (number | string)[]
  scale: (value: number | string) => number
  tickSize?: number
  className?: string
}

export function YAxis({
  ticks,
  scale,
  tickSize = 6,
  className,
}: YAxisProps) {
  return (
    <g className={className}>
      {ticks.map((tick, i) => {
        const y = scale(tick)
        return (
          <g key={i} transform={`translate(0,${y})`}>
            <line x2={-tickSize} stroke="currentColor" />
            <text
              x={-tickSize - 4}
              dy="0.32em"
              textAnchor="end"
              fontSize={12}
              fill="currentColor"
            >
              {String(tick)}
            </text>
          </g>
        )
      })}
    </g>
  )
}
