// packages/angular-switch/src/switch.component.ts
import { Component, Input, Output, EventEmitter, computed, signal, booleanAttribute } from '@angular/core';
import { createSwitch } from '@refraction-ui/switch';

@Component({
  selector: 're-switch',
  standalone: true,
  template: `
    <button
      type="button"
      [attr.role]="api().ariaProps.role"
      [attr.aria-checked]="api().ariaProps['aria-checked']"
      [attr.aria-disabled]="api().ariaProps['aria-disabled'] ? 'true' : null"
      [attr.data-state]="api().dataAttributes['data-state']"
      [attr.data-disabled]="api().dataAttributes['data-disabled']"
      [disabled]="api().state.disabled ? true : null"
      (click)="toggle()"
      (keydown)="onKeyDown($event)"
    >
      <ng-content></ng-content>
    </button>
  `
})
export class SwitchComponent {
  readonly checked = signal<boolean>(false);
  @Input({ transform: booleanAttribute }) set _checked(value: boolean) { this.checked.set(value); }

  readonly disabled = signal<boolean>(false);
  @Input({ transform: booleanAttribute }) set _disabled(value: boolean) { this.disabled.set(value); }

  @Output() checkedChange = new EventEmitter<boolean>();

  readonly api = computed(() => createSwitch({
    checked: this.checked(),
    disabled: this.disabled()
  }));

  toggle() {
    if (!this.api().isInteractive) return;
    const nextState = !this.checked();
    this.checked.set(nextState);
    this.checkedChange.emit(nextState);
  }

  onKeyDown(event: KeyboardEvent) {
    const handler = this.api().keyboardHandlers[event.key];
    if (handler) {
      handler(event as any);
    }
  }
}

// packages/react-switch/src/switch.tsx
import * as React from 'react'
import {
  createSwitch,
  switchVariants,
  switchThumbVariants,
} from '@refraction-ui/switch'
import { cn } from '@refraction-ui/shared'

export interface SwitchProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  checked?: boolean
  onCheckedChange?: (checked: boolean) => void
  disabled?: boolean
  size?: 'sm' | 'default' | 'lg'
}

/**
 * Switch component -- a toggle switch with accessible keyboard and ARIA support.
 *
 * Uses the headless @refraction-ui/switch core for state, ARIA, and keyboard handling.
 */
export const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  function Switch({ checked = false, onCheckedChange, disabled = false, size = 'default', className, ...props }, ref) {
    const api = createSwitch({ checked, disabled })

    const handleClick = () => {
      if (api.isInteractive) {
        onCheckedChange?.(!checked)
      }
    }

    const handleKeyDown = (e: React.KeyboardEvent<HTMLButtonElement>) => {
      if (e.key === ' ') {
        e.preventDefault()
        if (api.isInteractive) {
          onCheckedChange?.(!checked)
        }
      }
    }

    return (
      <button
        ref={ref}
        type="button"
        className={cn(switchVariants({ checked: checked ? 'true' : 'false', size }), className)}
        onClick={handleClick}
        onKeyDown={handleKeyDown}
        disabled={disabled}
        {...api.ariaProps}
        {...api.dataAttributes}
        {...props}
      >
        <span
          className={cn(switchThumbVariants({ checked: checked ? 'true' : 'false', size }))}
        />
      </button>
    )
  },
)
