// packages/angular-input/src/input.component.ts
import { Component, Input, computed, signal, booleanAttribute } from '@angular/core';
import { createInput, type InputType } from '@refraction-ui/input';

@Component({
  selector: 're-input',
  standalone: true,
  template: `
    <input
      [type]="type() || 'text'"
      [attr.disabled]="disabled() ? '' : null"
      [attr.readonly]="readOnly() ? '' : null"
      [attr.required]="required() ? '' : null"
      [attr.placeholder]="placeholder()"
      [attr.aria-invalid]="api().ariaProps['aria-invalid'] ? 'true' : null"
      [attr.aria-disabled]="api().ariaProps['aria-disabled'] ? 'true' : null"
      [attr.aria-required]="api().ariaProps['aria-required'] ? 'true' : null"
      [attr.data-disabled]="api().dataAttributes['data-disabled']"
      [attr.data-readonly]="api().dataAttributes['data-readonly']"
      [attr.data-invalid]="api().dataAttributes['data-invalid']"
    />
  `
})
export class InputComponent {
  readonly type = signal<InputType | undefined>(undefined);
  @Input('type') set _type(value: InputType | undefined) { this.type.set(value); }

  readonly disabled = signal<boolean>(false);
  @Input({ transform: booleanAttribute }) set _disabled(value: boolean) { this.disabled.set(value); }

  readonly readOnly = signal<boolean>(false);
  @Input({ transform: booleanAttribute }) set _readOnly(value: boolean) { this.readOnly.set(value); }

  readonly required = signal<boolean>(false);
  @Input({ transform: booleanAttribute }) set _required(value: boolean) { this.required.set(value); }

  readonly placeholder = signal<string | undefined>(undefined);
  @Input('placeholder') set _placeholder(value: string | undefined) { this.placeholder.set(value); }

  readonly ariaInvalid = signal<boolean>(false);
  @Input({ alias: 'aria-invalid', transform: booleanAttribute }) set _ariaInvalid(value: boolean) { this.ariaInvalid.set(value); }

  readonly api = computed(() => createInput({
    type: this.type(),
    disabled: this.disabled(),
    readOnly: this.readOnly(),
    required: this.required(),
    placeholder: this.placeholder(),
    'aria-invalid': this.ariaInvalid()
  }));
}

// packages/react-input/src/input.tsx
import * as React from 'react'
import {
  createInput,
  inputVariants,
} from '@refraction-ui/input'
import { cn } from '@refraction-ui/shared'

export interface InputProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {
  size?: 'sm' | 'default' | 'lg'
}

/**
 * Input component — renders a styled input with size support.
 *
 * Uses the headless @refraction-ui/input core for state, ARIA, and data attributes.
 * Styling via Tailwind utility classes (no external CSS-in-JS).
 */
export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ type = 'text', size, className, disabled, readOnly, required, 'aria-invalid': ariaInvalid, ...props }, ref) => {
    const api = createInput({
      type: type as import('@refraction-ui/input').InputType,
      disabled,
      readOnly,
      required,
      'aria-invalid': ariaInvalid === true ? true : undefined,
    })

    const classes = cn(inputVariants({ size }), className)

    return (
      <input
        ref={ref}
        type={type}
        className={classes}
        disabled={disabled}
        readOnly={readOnly}
        required={required}
        {...api.ariaProps}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

Input.displayName = 'Input'
