// packages/angular-data-table/src/data-table.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  computed,
  signal,
} from '@angular/core';
import {
  createDataTable,
  type ColumnDef,
  type SortDirection,
  tableVariants,
  headerVariants,
  cellVariants,
  rowVariants,
} from '@refraction-ui/data-table';

export interface SortChangeEvent {
  columnId: string;
  direction: SortDirection;
}

@Component({
  selector: 're-data-table',
  standalone: true,
  template: `
    <div [class]="customClass()" style="overflow-x: auto;">
      <table [class]="tableClass()" role="grid" [attr.aria-label]="ariaLabel()">
        <!-- Header -->
        <thead>
          <tr role="row">
            @for (col of columns(); track col.id) {
            <th
              [class]="getHeaderClass(col)"
              [attr.role]="'columnheader'"
              [attr.aria-sort]="getHeaderAriaSort(col)"
              [attr.data-column]="col.id"
              (click)="col.sortable ? onSort(col.id) : null"
            >
              <span style="display: inline-flex; align-items: center; gap: 4px;">
                {{ col.header }}
                @if (col.sortable) {
                  <span aria-hidden="true" style="font-size: 10px; opacity: 0.6;">
                    {{ getSortIndicator(col.id) }}
                  </span>
                }
              </span>
              @if (col.filterable) {
                <div style="margin-top: 4px;">
                  <input
                    type="text"
                    [value]="getFilterValue(col.id)"
                    (input)="onFilterInput(col.id, $event)"
                    [attr.aria-label]="'Filter ' + col.header"
                    placeholder="Filter..."
                    style="width: 100%; font-size: 11px; padding: 2px 4px; border: 1px solid currentColor; border-radius: 3px; background: transparent;"
                  />
                </div>
              }
            </th>
            }
          </tr>
        </thead>

        <!-- Body -->
        <tbody>
          @for (row of sortedData(); track rowTrackId(row, $index)) {
          <tr
            [class]="rowClass()"
            [attr.role]="'row'"
            [attr.data-row-index]="$index"
          >
            @for (col of columns(); track col.id) {
            <td
              [class]="cellClass()"
              role="cell"
              [attr.data-column]="col.id"
            >
              {{ getCellValue(col, row) }}
            </td>
            }
          </tr>
          } @empty {
          <tr role="row">
            <td
              [attr.colspan]="columns().length"
              [class]="cellClass()"
              style="text-align: center; opacity: 0.5;"
              role="cell"
            >
              No data
            </td>
          </tr>
          }
        </tbody>
      </table>
    </div>
  `,
})
export class DataTableComponent {
  // ── Signals for inputs ──────────────────────────────────────────────────
  readonly columns = signal<ColumnDef[]>([]);
  @Input('columns') set _columns(val: ColumnDef[]) {
    this.columns.set(val ?? []);
  }

  readonly data = signal<Record<string, unknown>[]>([]);
  @Input('data') set _data(val: Record<string, unknown>[]) {
    this.data.set(val ?? []);
  }

  readonly sortByInput = signal<string | undefined>(undefined);
  @Input('sortBy') set _sortBy(val: string | undefined) {
    this.sortByInput.set(val);
    // sync internal state
    if (val !== undefined) this._internalSortBy.set(val);
  }

  readonly sortDirInput = signal<SortDirection>('asc');
  @Input('sortDir') set _sortDir(val: SortDirection) {
    this.sortDirInput.set(val ?? 'asc');
    this._internalSortDir.set(val ?? 'asc');
  }

  readonly filtersInput = signal<Record<string, string>>({});
  @Input('filters') set _filters(val: Record<string, string>) {
    this.filtersInput.set(val ?? {});
    this._internalFilters.set(val ?? {});
  }

  readonly customClass = signal<string>('');
  @Input('class') set _class(val: string) {
    this.customClass.set(val ?? '');
  }

  readonly _ariaLabel = signal<string>('Data table');
  @Input('ariaLabel') set __ariaLabel(val: string) {
    this._ariaLabel.set(val ?? 'Data table');
  }

  // ── Outputs ──────────────────────────────────────────────────────────────
  @Output() sortChange = new EventEmitter<SortChangeEvent>();
  @Output() filterChange = new EventEmitter<{ columnId: string; value: string }>();

  // ── Internal reactive state ───────────────────────────────────────────
  readonly _internalSortBy = signal<string | undefined>(undefined);
  readonly _internalSortDir = signal<SortDirection>('asc');
  readonly _internalFilters = signal<Record<string, string>>({});

  // ── Computed API ─────────────────────────────────────────────────────
  readonly api = computed(() => {
    return createDataTable({
      columns: this.columns(),
      data: this.data(),
      sortBy: this._internalSortBy(),
      sortDir: this._internalSortDir(),
      filters: this._internalFilters(),
      onSort: (columnId: string, direction: SortDirection) => {
        this.sortChange.emit({ columnId, direction });
      },
    });
  });

  readonly sortedData = computed(() => this.api().state.sortedData);
  readonly ariaLabel = computed(() => this._ariaLabel());

  // ── CSS class helpers ────────────────────────────────────────────────
  readonly tableClass = computed(() => tableVariants());
  rowClass() { return rowVariants({ selected: 'false' }); }
  cellClass() { return cellVariants(); }

  getHeaderClass(col: ColumnDef): string {
    return headerVariants({ sortable: col.sortable ? 'true' : 'false' });
  }

  // ── Sort ─────────────────────────────────────────────────────────────
  onSort(columnId: string): void {
    const currentSortBy = this._internalSortBy();
    const currentDir = this._internalSortDir();

    let newDir: SortDirection = 'asc';
    if (currentSortBy === columnId) {
      newDir = currentDir === 'asc' ? 'desc' : 'asc';
    }

    this._internalSortBy.set(columnId);
    this._internalSortDir.set(newDir);

    this.sortChange.emit({ columnId, direction: newDir });
  }

  getHeaderAriaSort(col: ColumnDef): string | null {
    if (!col.sortable) return null;
    const sortBy = this._internalSortBy();
    if (sortBy !== col.id) return 'none';
    return this._internalSortDir() === 'asc' ? 'ascending' : 'descending';
  }

  getSortIndicator(columnId: string): string {
    if (this._internalSortBy() !== columnId) return '⇅';
    return this._internalSortDir() === 'asc' ? '↑' : '↓';
  }

  // ── Filter ───────────────────────────────────────────────────────────
  onFilterInput(columnId: string, event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    const current = { ...this._internalFilters() };
    current[columnId] = value;
    this._internalFilters.set(current);
    this.filterChange.emit({ columnId, value });
  }

  getFilterValue(columnId: string): string {
    return this._internalFilters()[columnId] ?? '';
  }

  // ── Cell value ───────────────────────────────────────────────────────
  getCellValue(col: ColumnDef, row: Record<string, unknown>): string {
    const val = col.accessor(row);
    return val != null ? String(val) : '';
  }

  // ── Row tracking ─────────────────────────────────────────────────────
  rowTrackId(row: Record<string, unknown>, index: number): unknown {
    return (row['id'] as unknown) ?? index;
  }
}

// packages/react-data-table/src/DataTable.tsx
import * as React from 'react'
import {
  createDataTable,
  tableVariants,
  headerVariants,
  cellVariants,
  rowVariants,
  type ColumnDef,
  type SortDirection,
} from '@refraction-ui/data-table'
import { cn } from '@refraction-ui/shared'

// ---------------------------------------------------------------------------
// DataTable
// ---------------------------------------------------------------------------

export interface DataTableProps<T = Record<string, unknown>> {
  columns: ColumnDef<T>[]
  data: T[]
  sortBy?: string
  sortDir?: SortDirection
  onSort?: (columnId: string, direction: SortDirection) => void
  filters?: Record<string, string>
  className?: string
  emptyMessage?: string
}

export function DataTable<T = Record<string, unknown>>({
  columns,
  data,
  sortBy: controlledSortBy,
  sortDir: controlledSortDir = 'asc',
  onSort,
  filters: controlledFilters,
  className,
  emptyMessage = 'No data available',
}: DataTableProps<T>) {
  const [sortBy, setSortBy] = React.useState<string | null>(controlledSortBy ?? null)
  const [sortDir, setSortDir] = React.useState<SortDirection>(controlledSortDir)
  const [filters, setFilters] = React.useState<Record<string, string>>(controlledFilters ?? {})

  const api = React.useMemo(
    () =>
      createDataTable<T>({
        columns,
        data,
        sortBy: sortBy ?? undefined,
        sortDir,
        onSort,
        filters,
      }),
    [columns, data, sortBy, sortDir, onSort, filters],
  )

  const handleSort = React.useCallback(
    (columnId: string) => {
      const col = columns.find((c) => c.id === columnId)
      if (!col?.sortable) return

      let newDir: SortDirection = 'asc'
      if (sortBy === columnId) {
        newDir = sortDir === 'asc' ? 'desc' : 'asc'
      }

      setSortBy(columnId)
      setSortDir(newDir)
      onSort?.(columnId, newDir)
    },
    [columns, sortBy, sortDir, onSort],
  )

  const handleFilter = React.useCallback(
    (columnId: string, value: string) => {
      setFilters((prev) => ({ ...prev, [columnId]: value }))
    },
    [],
  )

  const sortedData = api.state.sortedData
  const hasFilterable = columns.some((c) => c.filterable)

  return React.createElement(
    'div',
    { className: 'relative w-full overflow-auto' },
    React.createElement(
      'table',
      {
        className: cn(tableVariants(), className),
        role: 'table',
      },
      // thead
      React.createElement(
        'thead',
        null,
        // Header row
        React.createElement(
          'tr',
          { role: 'row' },
          ...columns.map((col) => {
            const headerProps = api.getHeaderProps(col)
            return React.createElement(
              'th',
              {
                key: col.id,
                ...headerProps,
                className: headerVariants({ sortable: col.sortable ? 'true' : 'false' }),
                onClick: col.sortable ? () => handleSort(col.id) : undefined,
              },
              col.header,
              col.sortable && sortBy === col.id
                ? React.createElement('span', { 'aria-hidden': true }, sortDir === 'asc' ? ' \u2191' : ' \u2193')
                : null,
            )
          }),
        ),
        // Filter row
        hasFilterable
          ? React.createElement(
              'tr',
              { role: 'row', 'data-filter-row': 'true' },
              ...columns.map((col) =>
                React.createElement(
                  'th',
                  { key: `filter-${col.id}` },
                  col.filterable
                    ? React.createElement('input', {
                        type: 'text',
                        'aria-label': `Filter ${col.header}`,
                        value: filters[col.id] ?? '',
                        onChange: (e: React.ChangeEvent<HTMLInputElement>) =>
                          handleFilter(col.id, e.target.value),
                        placeholder: `Filter...`,
                      })
                    : null,
                ),
              ),
            )
          : null,
      ),
      // tbody
      React.createElement(
        'tbody',
        null,
        sortedData.length === 0
          ? React.createElement(
              'tr',
              { role: 'row' },
              React.createElement(
                'td',
                {
                  colSpan: columns.length,
                  className: 'text-center p-4 text-muted-foreground',
                  role: 'cell',
                },
                emptyMessage,
              ),
            )
          : sortedData.map((row, rowIndex) =>
              React.createElement(
                'tr',
                {
                  key: rowIndex,
                  ...api.getRowProps(row, rowIndex),
                  className: rowVariants(),
                },
                ...columns.map((col) =>
                  React.createElement(
                    'td',
                    {
                      key: col.id,
                      ...api.getCellProps(col, row),
                      className: cellVariants(),
                    },
                    String(col.accessor(row) ?? ''),
                  ),
                ),
              ),
            ),
      ),
    )
  )
}

DataTable.displayName = 'DataTable'
