// packages/react-charts/src/circles.tsx
import * as React from 'react'
import { createLinearScale, computeExtent } from '@refraction-ui/charts'
import { useChartContext } from './chart-context.js'

export interface CirclesProps<T = unknown> {
  data: T[]
  cx: (d: T) => number
  cy: (d: T) => number
  r?: number
  fill?: string
  className?: string
}

export function Circles<T>({
  data,
  cx,
  cy,
  r = 4,
  fill = 'currentColor',
  className,
}: CirclesProps<T>) {
  const { dimensions } = useChartContext()
  const { boundedWidth, boundedHeight } = dimensions

  const xValues = data.map(cx)
  const yValues = data.map(cy)
  const [xMin, xMax] = computeExtent(xValues)
  const [yMin, yMax] = computeExtent(yValues)

  const xScale = createLinearScale([xMin, xMax], [0, boundedWidth])
  const yScale = createLinearScale([yMin, yMax], [boundedHeight, 0])

  return (
    <g className={className}>
      {data.map((d, i) => (
        <circle
          key={i}
          cx={xScale(cx(d))}
          cy={yScale(cy(d))}
          r={r}
          fill={fill}
        />
      ))}
    </g>
  )
}

// packages/angular-charts/src/circles.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { createLinearScale, computeExtent } from '@refraction-ui/charts';
import { ChartContextService } from './chart-context.service';

@Component({
  selector: '[re-circles]',
  standalone: true,
  imports: [CommonModule],
  template: `
    <svg:circle
      *ngFor="let circle of computedCircles"
      [attr.cx]="circle.cx"
      [attr.cy]="circle.cy"
      [attr.r]="radius"
      [attr.fill]="fill"
      [attr.stroke]="stroke"
      [attr.stroke-width]="strokeWidth"
    />
  `
})
export class CirclesComponent<T = any> {
  @Input() data: T[] = [];
  @Input() x!: (d: T) => number;
  @Input() y!: (d: T) => number;
  @Input() radius: number = 4;
  @Input() fill: string = 'currentColor';
  @Input() stroke: string = 'none';
  @Input() strokeWidth: number = 0;

  constructor(private contextService: ChartContextService) {}

  get computedCircles() {
    const dimensions = this.contextService.context().dimensions;
    const { boundedWidth, boundedHeight } = dimensions;

    const data = this.data;
    if (!data || !data.length || !this.x || !this.y) return [];

    const xVals = data.map(this.x);
    const yVals = data.map(this.y);
    const [minX, maxX] = computeExtent(xVals);
    const [minY, maxY] = computeExtent(yVals);

    const xScale = createLinearScale([minX as number, maxX as number], [0, boundedWidth]);
    const yScale = createLinearScale([minY as number, maxY as number], [boundedHeight, 0]);

    return data.map(d => ({
      cx: xScale(this.x(d)),
      cy: yScale(this.y(d))
    }));
  }
}
