// packages/react-bottom-nav/src/bottom-nav.tsx
import * as React from 'react'
import {
  createBottomNav,
  bottomNavVariants,
  bottomNavTabVariants,
  type NavTab,
} from '@refraction-ui/bottom-nav'
import { cn } from '@refraction-ui/shared'

export interface BottomNavProps extends React.HTMLAttributes<HTMLElement> {
  /** Tab items */
  tabs?: NavTab[]
  /** Current pathname for active state */
  currentPath?: string
}

/**
 * BottomNav component — renders a fixed bottom navigation bar with tab buttons.
 *
 * Uses the headless @refraction-ui/bottom-nav core for state and ARIA attributes.
 * Visible on mobile only (md:hidden via styles).
 */
export const BottomNav = React.forwardRef<HTMLElement, BottomNavProps>(
  function BottomNav({ tabs = [], currentPath, className, ...props }, ref) {
    const api = createBottomNav({ tabs, currentPath })
    const classes = cn(bottomNavVariants(), className)

    return (
      <nav ref={ref} className={classes} {...api.ariaProps} {...props}>
        <div className="flex">
          {tabs.map((tab) => {
            const active = api.isActive(tab.href)
            return (
              <a
                key={tab.href}
                href={tab.href}
                className={bottomNavTabVariants({ active: active ? 'true' : 'false' })}
                {...api.tabAriaProps(tab.href)}
              >
                {tab.icon && <span aria-hidden="true">{active && tab.activeIcon ? tab.activeIcon : tab.icon}</span>}
                <span>{tab.label}</span>
              </a>
            )
          })}
        </div>
      </nav>
    )
  },
)

// packages/angular-bottom-nav/src/bottom-nav.component.ts
import { Component, Input } from '@angular/core';
import {
  createBottomNav,
  bottomNavVariants,
  bottomNavTabVariants,
  type NavTab,
} from '@refraction-ui/bottom-nav';

@Component({
  selector: 're-bottom-nav',
  standalone: true,
  template: `
    <nav
      role="navigation"
      [attr.aria-label]="api.ariaProps['aria-label']"
      [class]="navClass"
    >
      <div style="display: flex;">
        @for (tab of tabsList; track tab.href) {
          <a
            [attr.href]="tab.href"
            [class]="getTabClass(tab.href)"
            [attr.aria-current]="getAriaCurrent(tab.href)"
          >
            @if (tab.icon) {
              <span aria-hidden="true">{{ getIcon(tab) }}</span>
            }
            <span>{{ tab.label }}</span>
          </a>
        }
      </div>
    </nav>
  `,
})
export class BottomNavComponent {
  @Input() tabs?: NavTab[];
  @Input() currentPath?: string;
  @Input() customClass?: string;

  get api() {
    return createBottomNav({ currentPath: this.currentPath });
  }

  get tabsList(): NavTab[] {
    return this.tabs || [];
  }

  get navClass(): string {
    return bottomNavVariants() + (this.customClass ? ' ' + this.customClass : '');
  }

  getTabClass(href: string): string {
    let active: 'true' | 'false' = 'false';
    if (this.api.isActive(href)) active = 'true';
    return bottomNavTabVariants({ active });
  }

  getAriaCurrent(href: string): string | null {
    return this.api.tabAriaProps(href)['aria-current'] || null;
  }

  getIcon(tab: NavTab): string {
    if (this.api.isActive(tab.href) && tab.activeIcon) {
      return tab.activeIcon;
    }
    return tab.icon || '';
  }
}
