// packages/angular-breadcrumbs/src/breadcrumbs.component.ts
import { Component, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { createBreadcrumbs, type BreadcrumbItem, type BreadcrumbsAPI } from '@refraction-ui/breadcrumbs';

@Component({
  selector: 'refraction-breadcrumbs',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav [attr.aria-label]="api.ariaProps['aria-label']">
      <ol class="flex items-center space-x-2">
        <li *ngFor="let item of api.items; let i = index" class="flex items-center">
          <ng-container *ngIf="item.href; else textOnly">
            <a [href]="item.href" [attr.aria-current]="api.itemAriaProps(i)['aria-current']">
              {{ item.label }}
            </a>
          </ng-container>
          <ng-template #textOnly>
            <span [attr.aria-current]="api.itemAriaProps(i)['aria-current']">
              {{ item.label }}
            </span>
          </ng-template>
          <span *ngIf="!api.isLast(i)" class="mx-2" aria-hidden="true">{{ api.separator }}</span>
        </li>
      </ol>
    </nav>
  `
})
export class BreadcrumbsComponent {
  @Input() pathname?: string;
  @Input() items?: BreadcrumbItem[];
  @Input() labels?: Record<string, string>;
  @Input() separator: string = '/';
  @Input() maxItems?: number;

  get api(): BreadcrumbsAPI {
    return createBreadcrumbs({
      pathname: this.pathname,
      items: this.items,
      labels: this.labels,
      separator: this.separator,
      maxItems: this.maxItems
    });
  }
}

// packages/react-breadcrumbs/src/breadcrumbs.tsx
import * as React from 'react'
import {
  createBreadcrumbs,
  breadcrumbsVariants,
  breadcrumbItemVariants,
  breadcrumbSeparatorStyles,
  type BreadcrumbItem,
} from '@refraction-ui/breadcrumbs'
import { cn } from '@refraction-ui/shared'

export interface BreadcrumbsProps extends React.HTMLAttributes<HTMLElement> {
  /** Current pathname to auto-generate breadcrumbs from */
  pathname?: string
  /** Manual breadcrumb items (overrides pathname) */
  items?: BreadcrumbItem[]
  /** Custom label map for pathname segments */
  labels?: Record<string, string>
  /** Separator character. Default: '/' */
  separator?: string
  /** Max items before truncation */
  maxItems?: number
}

/**
 * Breadcrumbs component — renders a breadcrumb navigation trail.
 *
 * Uses the headless @refraction-ui/breadcrumbs core for state and ARIA attributes.
 */
export const Breadcrumbs = React.forwardRef<HTMLElement, BreadcrumbsProps>(
  function Breadcrumbs(
    {
      pathname,
      items,
      labels,
      separator,
      maxItems,
      className,
      ...props
    },
    ref,
  ) {
    const api = createBreadcrumbs({ pathname, items, labels, separator, maxItems })
    const classes = cn(breadcrumbsVariants(), className)

    return (
      <nav ref={ref} className={classes} {...api.ariaProps} {...props}>
        <ol className="flex items-center gap-1.5">
          {api.items.map((item, index) => {
            const isLast = api.isLast(index)
            return (
              <li key={index} className="flex items-center gap-1.5">
                {index > 0 && (
                  <span className={breadcrumbSeparatorStyles} aria-hidden="true">
                    {api.separator}
                  </span>
                )}
                {item.href && !isLast ? (
                  <a
                    href={item.href}
                    className={breadcrumbItemVariants({ active: 'false' })}
                  >
                    {item.label}
                  </a>
                ) : (
                  <span
                    className={breadcrumbItemVariants({
                      active: isLast ? 'true' : 'false',
                    })}
                    {...api.itemAriaProps(index)}
                  >
                    {item.label}
                  </span>
                )}
              </li>
            )
          })}
        </ol>
      </nav>
    )
  },
)
