// packages/vue-payment/src/Payment.vue
<template>
  <div class="refraction-payment">
    <div id="payment-element-placeholder">Payment Element Placeholder (Vue)</div>
    <button @click="handlePay">Pay</button>
  </div>
</template>

<script setup lang="ts">
import { defineProps, onMounted } from 'vue';
import type { PaymentProps } from '@refraction-ui/payment';

interface Props extends PaymentProps {
  stripeKey: string;
}

const props = defineProps<Props>();

onMounted(() => {
  console.log('Stripe initialized in Vue component with clientSecret:', props.clientSecret);
});

const handlePay = () => {
  console.log('Pay button clicked');
};
</script>

// packages/angular-payment/src/payment.component.ts
import { Component, Input, OnInit } from '@angular/core';
import type { PaymentProps } from '@refraction-ui/payment';

@Component({
  selector: 'ref-payment',
  template: `
    <div class="refraction-payment">
      <div id="payment-element-placeholder">Payment Element Placeholder (Angular)</div>
      <button>Pay</button>
    </div>
  `
})
export class PaymentComponent implements OnInit, PaymentProps {
  @Input() clientSecret?: string;
  @Input() stripeKey?: string;

  ngOnInit() {
    console.log('Stripe initialized in Angular component.');
  }
}
