// packages/react-callout/src/callout.tsx
import * as React from 'react'
import {
  createCallout,
  createCalloutIcon,
  createCalloutContent,
  createCalloutTitle,
  createCalloutDescription,
  calloutVariants,
  calloutTitleVariants,
  calloutDescriptionVariants,
} from '@refraction-ui/callout'
import { cn } from '@refraction-ui/shared'

export interface CalloutProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'default' | 'destructive' | 'success' | 'warning' | 'info'
}

export const Callout = React.forwardRef<HTMLDivElement, CalloutProps>(
  function Callout({ className, variant, ...props }, ref) {
    const api = createCallout({ role: variant === 'destructive' ? 'alert' : 'region' })
    return (
      <div
        ref={ref}
        className={cn(calloutVariants({ variant }), className)}
        {...api.ariaProps}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

export const CalloutIcon = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  function CalloutIcon({ className, ...props }, ref) {
    const api = createCalloutIcon()
    return (
      <div
        ref={ref}
        className={cn('flex-shrink-0 mt-0.5', className)}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

export const CalloutContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  function CalloutContent({ className, ...props }, ref) {
    const api = createCalloutContent()
    return (
      <div
        ref={ref}
        className={cn('flex-1', className)}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

export const CalloutTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  function CalloutTitle({ className, ...props }, ref) {
    const api = createCalloutTitle()
    return (
      <h5
        ref={ref}
        className={cn(calloutTitleVariants(), className)}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

export const CalloutDescription = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  function CalloutDescription({ className, ...props }, ref) {
    const api = createCalloutDescription()
    return (
      <div
        ref={ref}
        className={cn(calloutDescriptionVariants(), className)}
        {...api.dataAttributes}
        {...props}
      />
    )
  },
)

// packages/angular-callout/src/callout.component.ts
import { Component, Input, HostBinding } from '@angular/core'
import {
  createCallout,
  createCalloutIcon,
  createCalloutContent,
  createCalloutTitle,
  createCalloutDescription,
  calloutVariants,
  calloutTitleVariants,
  calloutDescriptionVariants,
} from '@refraction-ui/callout'
import { cn } from '@refraction-ui/shared'

@Component({
  selector: 'app-callout, [app-callout]',
  template: '<ng-content></ng-content>',
  standalone: true,
})
export class CalloutComponent {
  @Input() variant: 'default' | 'destructive' | 'success' | 'warning' | 'info' = 'default'
  @Input() class = ''

  private get api() {
    return createCallout({ role: this.variant === 'destructive' ? 'alert' : 'region' })
  }

  @HostBinding('class') get hostClass() {
    return cn(calloutVariants({ variant: this.variant }), this.class)
  }

  @HostBinding('attr.role') get role() {
    return this.api.ariaProps.role
  }

  @HostBinding('attr.data-slot') get dataSlot() {
    return this.api.dataAttributes['data-slot']
  }
}

@Component({
  selector: 'app-callout-icon, [app-callout-icon]',
  template: '<ng-content></ng-content>',
  standalone: true,
})
export class CalloutIconComponent {
  @Input() class = ''

  private get api() {
    return createCalloutIcon()
  }

  @HostBinding('class') get hostClass() {
    return cn('flex-shrink-0 mt-0.5', this.class)
  }

  @HostBinding('attr.data-slot') get dataSlot() {
    return this.api.dataAttributes['data-slot']
  }
}

@Component({
  selector: 'app-callout-content, [app-callout-content]',
  template: '<ng-content></ng-content>',
  standalone: true,
})
export class CalloutContentComponent {
  @Input() class = ''

  private get api() {
    return createCalloutContent()
  }

  @HostBinding('class') get hostClass() {
    return cn('flex-1', this.class)
  }

  @HostBinding('attr.data-slot') get dataSlot() {
    return this.api.dataAttributes['data-slot']
  }
}

@Component({
  selector: 'app-callout-title, [app-callout-title]',
  template: '<ng-content></ng-content>',
  standalone: true,
})
export class CalloutTitleComponent {
  @Input() class = ''

  private get api() {
    return createCalloutTitle()
  }

  @HostBinding('class') get hostClass() {
    return cn(calloutTitleVariants(), this.class)
  }

  @HostBinding('attr.data-slot') get dataSlot() {
    return this.api.dataAttributes['data-slot']
  }
}

@Component({
  selector: 'app-callout-description, [app-callout-description]',
  template: '<ng-content></ng-content>',
  standalone: true,
})
export class CalloutDescriptionComponent {
  @Input() class = ''

  private get api() {
    return createCalloutDescription()
  }

  @HostBinding('class') get hostClass() {
    return cn(calloutDescriptionVariants(), this.class)
  }

  @HostBinding('attr.data-slot') get dataSlot() {
    return this.api.dataAttributes['data-slot']
  }
}
