// packages/react-calendar/src/calendar.tsx
import * as React from 'react'
import {
  createCalendar,
  calendarVariants,
  dayVariants,
  type CalendarProps as CoreCalendarProps,
  type CalendarDay,
} from '@refraction-ui/calendar'
import { cn } from '@refraction-ui/shared'

// ---------------------------------------------------------------------------
// Calendar
// ---------------------------------------------------------------------------

export interface CalendarProps extends CoreCalendarProps {
  className?: string
  children?: React.ReactNode
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
]

const DAY_HEADERS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa']

export function Calendar({
  className,
  value,
  defaultValue,
  onSelect,
  month,
  onMonthChange,
  minDate,
  maxDate,
  disabledDates,
}: CalendarProps) {
  const [uncontrolledValue, setUncontrolledValue] = React.useState<Date | undefined>(defaultValue)
  const [uncontrolledMonth, setUncontrolledMonth] = React.useState<Date>(
    () => month ?? value ?? defaultValue ?? new Date(),
  )

  const isValueControlled = value !== undefined
  const isMonthControlled = month !== undefined

  const selectedValue = isValueControlled ? value : uncontrolledValue
  const displayMonth = isMonthControlled ? month : uncontrolledMonth

  const handleSelect = React.useCallback(
    (date: Date) => {
      if (!isValueControlled) {
        setUncontrolledValue(date)
      }
      onSelect?.(date)
    },
    [isValueControlled, onSelect],
  )

  const handleMonthChange = React.useCallback(
    (m: Date) => {
      if (!isMonthControlled) {
        setUncontrolledMonth(m)
      }
      onMonthChange?.(m)
    },
    [isMonthControlled, onMonthChange],
  )

  const api = createCalendar({
    value: selectedValue,
    month: displayMonth,
    onSelect: handleSelect,
    onMonthChange: handleMonthChange,
    minDate,
    maxDate,
    disabledDates,
  })

  function getDayState(day: CalendarDay): 'selected' | 'today' | 'disabled' | 'outside' | 'default' {
    if (day.isDisabled) return 'disabled'
    if (day.isSelected) return 'selected'
    if (!day.isCurrentMonth) return 'outside'
    if (day.isToday) return 'today'
    return 'default'
  }

  const monthLabel = `${MONTH_NAMES[api.state.currentMonth.getMonth()]} ${api.state.currentMonth.getFullYear()}`

  return React.createElement(
    'div',
    {
      className: cn(calendarVariants(), className),
      ...api.ariaProps,
    },
    // Header row: prev, month label, next
    React.createElement(CalendarHeader, {
      label: monthLabel,
      labelId: api.ids.label,
      onPrevMonth: api.prevMonth,
      onNextMonth: api.nextMonth,
    }),
    // Day-of-week headers
    React.createElement(
      'div',
      {
        className: 'grid grid-cols-7 gap-1 mb-1',
        role: 'row',
      },
      DAY_HEADERS.map((d) =>
        React.createElement(
          'div',
          {
            key: d,
            className: 'text-center text-xs font-medium text-muted-foreground h-9 flex items-center justify-center',
            role: 'columnheader',
            'aria-label': d,
          },
          d,
        ),
      ),
    ),
    // Day grid
    React.createElement(
      'div',
      {
        className: 'grid grid-cols-7 gap-1',
        role: 'rowgroup',
      },
      api.days.map((day, i) => {
        const dayAriaProps = api.getDayAriaProps(day)
        const state = getDayState(day)
        return React.createElement(
          'button',
          {
            key: i,
            type: 'button',
            className: dayVariants({ state }),
            disabled: day.isDisabled,
            onClick: () => api.select(day.date),
            ...dayAriaProps,
          },
          day.date.getDate(),
        )
      }),
    ),
  )
}

Calendar.displayName = 'Calendar'

// ---------------------------------------------------------------------------
// CalendarHeader
// ---------------------------------------------------------------------------

export interface CalendarHeaderProps {
  label: string
  labelId: string
  onPrevMonth: () => void
  onNextMonth: () => void
  className?: string
}

export function CalendarHeader({
  label,
  labelId,
  onPrevMonth,
  onNextMonth,
  className,
}: CalendarHeaderProps) {
  return React.createElement(
    'div',
    {
      className: cn('flex items-center justify-between mb-2', className),
    },
    React.createElement(
      'button',
      {
        type: 'button',
        'aria-label': 'Previous month',
        onClick: onPrevMonth,
        className: 'inline-flex items-center justify-center h-7 w-7 rounded-md hover:bg-accent',
      },
      '\u2039',
    ),
    React.createElement(
      'div',
      {
        id: labelId,
        className: 'text-sm font-medium',
        'aria-live': 'polite',
      },
      label,
    ),
    React.createElement(
      'button',
      {
        type: 'button',
        'aria-label': 'Next month',
        onClick: onNextMonth,
        className: 'inline-flex items-center justify-center h-7 w-7 rounded-md hover:bg-accent',
      },
      '\u203A',
    ),
  )
}

CalendarHeader.displayName = 'CalendarHeader'

// packages/angular-calendar/src/calendar.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  computed,
  signal,
} from '@angular/core';
import {
  createCalendar,
  type CalendarDay,
  calendarVariants,
  dayVariants,
} from '@refraction-ui/calendar';

const DAY_HEADERS = ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'];

@Component({
  selector: 're-calendar',
  standalone: true,
  template: `
    <div
      [class]="calendarClasses()"
      [attr.id]="api().ids.grid"
      [attr.role]="api().ariaProps['role']"
      [attr.aria-labelledby]="api().ariaProps['aria-labelledby']"
    >
      <!-- Header row: prev, month label, next -->
      <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 8px;">
        <button
          type="button"
          aria-label="Previous month"
          (click)="prevMonth()"
          style="display: inline-flex; align-items: center; justify-content: center; height: 28px; width: 28px; border-radius: 6px; cursor: pointer;"
        >
          &lsaquo;
        </button>
        <div
          [attr.id]="api().ids.label"
          style="font-size: 14px; font-weight: 500;"
          aria-live="polite"
        >
          {{ monthLabel() }}
        </div>
        <button
          type="button"
          aria-label="Next month"
          (click)="nextMonth()"
          style="display: inline-flex; align-items: center; justify-content: center; height: 28px; width: 28px; border-radius: 6px; cursor: pointer;"
        >
          &rsaquo;
        </button>
      </div>

      <!-- Day-of-week headers -->
      <div
        style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 4px; margin-bottom: 4px;"
        role="row"
      >
        @for (header of dayHeaders; track header) {
        <div
          style="text-align: center; font-size: 12px; font-weight: 500; height: 36px; display: flex; align-items: center; justify-content: center;"
          role="columnheader"
          [attr.aria-label]="header"
        >
          {{ header }}
        </div>
        }
      </div>

      <!-- Day grid -->
      <div
        style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 4px;"
        role="rowgroup"
      >
        @for (day of days(); track day.date.toISOString()) {
        <button
          type="button"
          [class]="getDayClass(day)"
          [disabled]="day.isDisabled"
          [attr.role]="getDayAriaProps(day)['role']"
          [attr.aria-selected]="getDayAriaProps(day)['aria-selected']"
          [attr.aria-disabled]="getDayAriaProps(day)['aria-disabled']"
          [attr.aria-current]="getDayAriaProps(day)['aria-current']"
          [attr.aria-label]="getDayAriaProps(day)['aria-label']"
          (click)="selectDate(day.date)"
        >
          {{ day.date.getDate() }}
        </button>
        }
      </div>
    </div>
  `,
})
export class CalendarComponent {
  readonly dayHeaders = DAY_HEADERS;
  private readonly monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];

  // Inputs
  readonly value = signal<Date | undefined>(undefined);
  @Input('value') set _value(val: Date | string | undefined) {
    this.value.set(val ? new Date(val) : undefined);
  }

  readonly defaultValue = signal<Date | undefined>(undefined);
  @Input('defaultValue') set _defaultValue(val: Date | string | undefined) {
    this.defaultValue.set(val ? new Date(val) : undefined);
  }

  readonly minDate = signal<Date | undefined>(undefined);
  @Input('minDate') set _minDate(val: Date | string | undefined) {
    this.minDate.set(val ? new Date(val) : undefined);
  }

  readonly maxDate = signal<Date | undefined>(undefined);
  @Input('maxDate') set _maxDate(val: Date | string | undefined) {
    this.maxDate.set(val ? new Date(val) : undefined);
  }

  readonly disabledDates = signal<Date[]>([]);
  @Input('disabledDates') set _disabledDates(val: (Date | string)[]) {
    this.disabledDates.set(val ? val.map((d) => new Date(d)) : []);
  }

  readonly customClass = signal<string>('');
  @Input('class') set _customClass(val: string) {
    this.customClass.set(val || '');
  }

  // Month input/state
  readonly inputMonth = signal<Date | undefined>(undefined);
  @Input('month') set _month(val: Date | string | undefined) {
    this.inputMonth.set(val ? new Date(val) : undefined);
  }

  readonly internalMonth = signal<Date | undefined>(undefined);

  readonly currentDisplayMonth = computed(() => {
    return this.inputMonth() ?? this.internalMonth() ?? this.value() ?? this.defaultValue() ?? new Date();
  });

  // Outputs
  @Output() valueChange = new EventEmitter<Date>();
  @Output() monthChange = new EventEmitter<Date>();

  readonly api = computed(() => {
    return createCalendar({
      value: this.value(),
      defaultValue: this.defaultValue(),
      minDate: this.minDate(),
      maxDate: this.maxDate(),
      disabledDates: this.disabledDates(),
      month: this.currentDisplayMonth(),
    });
  });

  readonly days = computed(() => this.api().days);

  readonly monthLabel = computed(() => {
    const month = this.api().state.currentMonth;
    return `${this.monthNames[month.getMonth()]} ${month.getFullYear()}`;
  });

  readonly calendarClasses = computed(() => {
    // Uses clsx/tailwind-merge via cva under the hood from calendarVariants if we import cn
    return calendarVariants() + (this.customClass() ? ' ' + this.customClass() : '');
  });

  prevMonth(): void {
    const current = this.api().state.currentMonth;
    const prev = new Date(current.getFullYear(), current.getMonth() - 1, 1);
    if (!this.inputMonth()) {
      this.internalMonth.set(prev);
    }
    this.monthChange.emit(prev);
  }

  nextMonth(): void {
    const current = this.api().state.currentMonth;
    const next = new Date(current.getFullYear(), current.getMonth() + 1, 1);
    if (!this.inputMonth()) {
      this.internalMonth.set(next);
    }
    this.monthChange.emit(next);
  }

  selectDate(date: Date): void {
    // If uncontrolled value (we shouldn't maintain full internal value state unless requested, but usually the parent updates value)
    // Actually, createCalendar handles selection logic via onSelect, but in Angular it's simpler to emit.
    this.valueChange.emit(date);
  }

  getDayClass(day: CalendarDay): string {
    let state: 'default' | 'selected' | 'today' | 'disabled' | 'outside' = 'default';
    if (day.isDisabled) state = 'disabled';
    else if (day.isSelected) state = 'selected';
    else if (!day.isCurrentMonth) state = 'outside';
    else if (day.isToday) state = 'today';
    return dayVariants({ state });
  }

  getDayAriaProps(day: CalendarDay) {
    return this.api().getDayAriaProps(day);
  }
}
